### ISSUE TITLE
Editor: v0.2 to-do list

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/PhoneIDE#10]
**Editor:**

- [ ]  The editor should not automatically save files when new content is added to them.
- [ ]  The editor should recognize which language is being written in.
- [ ]  The editor should have CSS-syntax highlighting 
- [x]  The editor should have JS-syntax highlighting
